#!/usr/bin/env bash
# Write a Bash script that displays the content of the file /etc/passwd.

filename="/etc/passwd"

while IFS=: read -r username pass u_id g_id u_info home cmd
do
    echo "The user $username is part of the $g_id gang, lives in $home and rides $cmd. $u_id's place is protected by the passcode $pass, more info about the user here: $u_info"
    done < "$filename"
