#!/usr/bin/env bash
#this script is displaying "Holberton School",in the line number 9 its show "Hi"
i=0
while [ $i -lt 10 ];
do
      if [ $i -eq 9 ];
      then
	  echo "Hi"
      fi
          echo "Holberton School"
          let i=i+1
done
